// BOTON
export const BOTON_INICIO_MOSTRAR = 'BOTON_INICIO_MOSTRAR';
export const BOTON_PERFIL_MOSTRAR = 'BOTON_PERFIL_MOSTRAR';
export const BOTON_SALDO_MOSTRAR = 'BOTON_SALDO_MOSTRAR';
export const BOTON_JUGAR_MOSTRAR = 'BOTON_JUGAR_MOSTRAR';
export const BOTON_JUGAR1_MOSTRAR = 'BOTON_JUGAR1_MOSTRAR';
export const BOTON_JUGAR2_MOSTRAR = 'BOTON_JUGAR2_MOSTRAR';

// JUGADA
export const JUGADA_OBTENER = 'JUGADA_OBTENER';
export const JUGADA_AGREGAR = 'JUGADA_AGREGAR';

// ALERTA
export const ALERTA_MOSTRAR = 'ALERTA_MOSTRAR';
export const ALERTA_OCULTAR = 'ALERTA_OCULTAR';

// AUTENTICACION
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const ACTUALIZAR_USUARIO ='ACTUALIZAR_USUARIO';

// SALDO
export const SALDO_AGREGAR = 'SALDO_AGREGAR';
export const SALDO_OBTENER = 'SALDO_OBTENER';
export const SALDO_ACTUALIZAR = 'SALDO_ACTUALIZAR';
export const SALDO_MOSTRAR = 'SALDO_MOSTRAR';